/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    IconApps: typeof import('./src/components/icons/xicons/tabler/IconApps.vue')['default']
    IconCube: typeof import('./src/components/icons/xicons/tabler/IconCube.vue')['default']
    IconDotsVertical: typeof import('./src/components/icons/xicons/tabler/IconDotsVertical.vue')['default']
    IconDownload: typeof import('./src/components/icons/xicons/tabler/IconDownload.vue')['default']
    IconEye: typeof import('./src/components/icons/xicons/tabler/IconEye.vue')['default']
    IconEyeOff: typeof import('./src/components/icons/xicons/tabler/IconEyeOff.vue')['default']
    IconHeart: typeof import('./src/components/icons/xicons/tabler/IconHeart.vue')['default']
    IconLogin: typeof import('./src/components/icons/xicons/tabler/IconLogin.vue')['default']
    IconLogo: typeof import('./src/components/icons/IconLogo.vue')['default']
    IconStar: typeof import('./src/components/icons/xicons/tabler/IconStar.vue')['default']
    IconTitle: typeof import('./src/components/icons/IconTitle.vue')['default']
    ItemRenderer: typeof import('./src/components/renderers/ItemRenderer.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NFlex: typeof import('naive-ui')['NFlex']
    NH1: typeof import('naive-ui')['NH1']
    NIcon: typeof import('naive-ui')['NIcon']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NText: typeof import('naive-ui')['NText']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StructureRenderer: typeof import('./src/components/renderers/StructureRenderer.vue')['default']
    UserCard: typeof import('./src/components/users/UserCard.vue')['default']
  }
}
